// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfvlGBdTgWSanRi98NgiybUwylr3tvlQw',
    appId: '1:472813293545:web:dc18a8d43598965a72c578',
    messagingSenderId: '472813293545',
    projectId: 'apodel-restorant',
    authDomain: 'apodel-restorant.firebaseapp.com',
    storageBucket: 'apodel-restorant.firebasestorage.app',
    measurementId: 'G-NXXSLZRGQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWWNMSmgcx0lwhhfK1Nz7y5ElI1gheFX0',
    appId: '1:472813293545:android:b931c78fd619a57372c578',
    messagingSenderId: '472813293545',
    projectId: 'apodel-restorant',
    storageBucket: 'apodel-restorant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbblJT7w1Y6icHzmr2-Jw7Zu1CqEHLA2U',
    appId: '1:472813293545:ios:4099ccffe30e0f7672c578',
    messagingSenderId: '472813293545',
    projectId: 'apodel-restorant',
    storageBucket: 'apodel-restorant.firebasestorage.app',
    iosClientId: '472813293545-4k0002i2m5pvhnt9qerpl5n8vdt1e354.apps.googleusercontent.com',
    iosBundleId: 'app.apodel.restorant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbblJT7w1Y6icHzmr2-Jw7Zu1CqEHLA2U',
    appId: '1:472813293545:ios:a73249cad2807a5572c578',
    messagingSenderId: '472813293545',
    projectId: 'apodel-restorant',
    storageBucket: 'apodel-restorant.firebasestorage.app',
    iosClientId: '472813293545-n54nlrukihnu43b4l23tjhair5ohmgq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.apodelRestorant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfvlGBdTgWSanRi98NgiybUwylr3tvlQw',
    appId: '1:472813293545:web:0727e4e7bf500da372c578',
    messagingSenderId: '472813293545',
    projectId: 'apodel-restorant',
    authDomain: 'apodel-restorant.firebaseapp.com',
    storageBucket: 'apodel-restorant.firebasestorage.app',
    measurementId: 'G-Q1WJ3V7DVL',
  );
}
